/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Henk Kodde <henk.kodde@modusbox.com>
 --------------
 ******'/

@startuml
' declaring skinparam
skinparam sequenceMessageAlign center

' declare title
' title Customer-Initiated Merchant Payment example

' Actor Keys:
' participant - FSP or Switch
' actor - Payee, Payer or Payer(OTC)

' declare actors
actor "Payer" as Payer
participant "Payer FSP" as PayerFSP
participant "Switch" as SWITCH
participant "Payee FSP" as PayeeFSP
actor "Payee" as Payee
actor "Payer\n (OTC)" as PayerOTC

' start flow

' activate Payer
Payee <<- PayerOTC: I would like to buy\n this goods or service
Payee ->> PayerOTC: The goods or service cost\n 100 USD before any fees,\n please initiate the transaction
Payer ->> PayerFSP: I would like Payee to\n receive 100 USD
activate PayerFSP
PayerFSP ->> SWITCH: **POST /quotes**\n (amountType = RECEIVE,\n amount = 100 USD)
activate SWITCH
PayerFSP <<-- SWITCH: **HTTP 202** (Accepted)
SWITCH ->> PayeeFSP: **POST /quotes**\n (amountType = REVEIVE,\n amount = 100 USD)
activate PayeeFSP
SWITCH <<-- PayeeFSP: **HTTP 202** (Accepted)
PayeeFSP -> PayeeFSP: Interoperable fee is 0 USD in\n Payee FSP for Merchant\n Payment, but 1 USD in\n internal Payee fee for Merchant
SWITCH <<- PayeeFSP: **PUT /quotes/**<i><ID></i> \n(transferAmount = 100 USD)
SWITCH -->> PayeeFSP: **HTTP 200** (OK)
deactivate PayeeFSP
PayerFSP <<- SWITCH: **PUT /quotes/**<i><ID></i>\n (transferAmount = 100 USD)
PayerFSP -->> SWITCH: **HTTP 200** (OK)
deactivate SWITCH
PayerFSP -> PayerFSP: Fee is 1 USD in Payer\n FSP for Merchant Payment,\n total fee is 1 USD
Payer <<- PayerFSP: Will you approve Merchant Payment\n of 100 USD to Payee? It will\n cost you 1 USD in fees.
deactivate PayerFSP
' deactivate Payer
Payer ->> PayerFSP: Perform transaction
activate PayerFSP
PayerFSP -> PayerFSP: Reserve 101 USD from Payer\n account, 100 USD to Switch\n account and 1 USD to\n fee account
PayerFSP ->> SWITCH: **POST /transfer**\n (amount = 100 USD)
activate SWITCH
PayerFSP <<-- SWITCH: **HTTP 202** (Accepted)
SWITCH -> SWITCH: Reserve 100 USD from Payer FSP\n account to Payee FSP account
SWITCH ->> PayeeFSP: **POST /transfer**\n (amount = 100 USD)
activate PayeeFSP
SWITCH <<-- PayeeFSP: **HTTP 202** (Accepted)
PayeeFSP -> PayeeFSP: Transfer 100 USD from Switch\n account to Payee account, 1 USD\n from Payee to fee account
PayeeFSP ->> Payee: You have received 100 USD\n from Payer and paid 1 USD\n in internal fee. Please give\n goods or service to Payer.
Payee ->> PayerOTC: Here is your goods or service
SWITCH <<- PayeeFSP: **PUT /transfer/**<i><ID></i>
SWITCH -->> PayeeFSP: **HTTP 200** (OK)
deactivate PayeeFSP
SWITCH -> SWITCH: Commit reserved transfer
PayerFSP <<- SWITCH: **PUT /transfer/**<i><ID></i>
PayerFSP -->> SWITCH: **HTTP 200** (OK)
deactivate SWITCH
PayerFSP -> PayerFSP: Commit reserved transfer
Payer <<- PayerFSP: Payment successful, you\n have paid 100 USD to Payee\n plus 1 USD in fees
deactivate PayerFSP
@enduml
