/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Henk Kodde <henk.kodde@modusbox.com>
 --------------
 ******'/

@startuml
' declaring skinparam
skinparam sequenceMessageAlign center

' declare title
' title Merchant-Initiated Merchant Payment example

' Actor Keys:
' participant - FSP or Switch
' actor - Payee, Payer or Payer(OTC)

' declare actors
actor "Payer" as Payer
participant "Payer FSP" as PayerFSP
participant "Switch" as SWITCH
participant "Payee FSP" as PayeeFSP
actor "Payee\n(Agent)" as Payee
actor "Payer\n(OTC)" as PayerOTC

' start flow

Payee <<- PayerOTC: I would like to buy goods\n or service for 100 USD
PayeeFSP <<- Payee: I would like to receive\n 100 USD from Payer
activate PayeeFSP
PayeeFSP ->> SWITCH: **POST /TransactionRequests**\n (amount = 100 USD)
activate SWITCH
PayeeFSP <<-- SWITCH: **HTTP 202** (Accepted)
activate PayerFSP
PayerFSP <<- SWITCH: **POST /transactionRequests\n (amount = 100 USD)
PayerFSP -->> SWITCH: **HTTP 202** (Accepted)
PayerFSP -> PayerFSP: Perform optional validation
PayerFSP ->> SWITCH: **PUT /transactionRequests/**<i><ID></i>\n (Receives status)
PayerFSP <<-- SWITCH: **HTTP 200** (OK)
deactivate PayerFSP
SWITCH ->> PayeeFSP: **PUT /transactionRequests/**<i><ID></i>\n (Received status)
SWITCH <<-- PayeeFSP: **HTTP 200** (OK)
deactivate SWITCH
deactivate PayeeFSP
PayerFSP ->> SWITCH: **POST /quotes**\n (amountType = RECEIVE,\n amount = 100 USD)
activate PayerFSP
activate SWITCH
PayerFSP <<-- SWITCH: **HTTP 202** (Accepted)
SWITCH ->> PayeeFSP: **POST /quotes**\n (amountType = RECEIVE,\n amount = 100 USD)
activate PayeeFSP
SWITCH <<-- PayeeFSP: **HTTP 202** (Accepted)
PayeeFSP -> PayeeFSP: Fee is 0 USD
SWITCH <<- PayeeFSP: **PUT /quotes**<i><ID></i>\n (transferAmount = 100 USD,\n payeeFSPFee = 2 USD)
SWITCH -->> PayeeFSP: **HTTP 200** (OK)
deactivate PayeeFSP
SWITCH ->> PayerFSP: **PUT /quotes**<i><ID></i>\n (transferAmount = 100 USD,\n payeeFSPFee = 2 USD)
SWITCH <<-- PayerFSP: **HTTP 200** (OK)
deactivate SWITCH
PayerFSP -> PayerFSP: Payer fee is 1 USD in Payer\n FSP for Merchant Payment
Payer <<- PayerFSP: Will you approve Merchant Payment\n of 100 USD to Payee? It will\n cost you 1 USD in fees.
deactivate PayerFSP
Payer ->> PayerFSP: Perform transaction
activate PayerFSP
PayerFSP -> PayerFSP: Reserve 101 USD from Payer\n account, 100 USD to Switch\n account, 1 USD to fee account
PayerFSP ->> SWITCH: **POST /transfers**\n (amount = 100 USD)
activate SWITCH
PayerFSP <<-- SWITCH: **HTTP 202** (Accepted)
SWITCH -> SWITCH: Reserve 100 USD from Payer FSP\n account to Payee FSP account
SWITCH ->> PayeeFSP: **POST /transfers/**\n (amount = 100 USD)
activate PayeeFSP
SWITCH <<-- PayeeFSP: **HTTP 202** (Accepted)
PayeeFSP -> PayeeFSP: Transfer 100 USD from Switch\n account to Payee account
PayeeFSP ->> Payee: You have received 100 USD\n from Payer. Please give goods\n or service to Payer
Payee ->> PayerOTC: Here is your goods or service
SWITCH <<- PayeeFSP: **PUT /transfers/**<i><ID></i>
SWITCH -->> PayeeFSP: **HTTP 200** (OK)
deactivate PayeeFSP
SWITCH -> SWITCH: Commit reserved transfer
PayerFSP <<- SWITCH: PUT /transfers/<ID>
PayerFSP ->> SWITCH: **HTTP 200** (OK)
deactivate SWITCH
PayerFSP -> PayerFSP: Commit reserved transfer
Payer <<- PayerFSP: Transaction successful,\n you have paid 100 USD to Payee\n plus 1 USD in fees.


deactivate PayerFSP
@enduml
